/*
* generated by Xtext
*/
package jp.ac.kyushu.iarch.archdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ArchDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("jp/ac/kyushu/iarch/archdsl/parser/antlr/internal/InternalArchDSL.tokens");
	}
}
