/*
 * generated by Xtext
 */
package jp.ac.kyushu.iarch.archdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractArchDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(jp.ac.kyushu.iarch.archdsl.archDSL.ArchDSLPackage.eINSTANCE);
		return result;
	}
}
