/*
* generated by Xtext
*/
package jp.ac.kyushu.iarch.archdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ArchDSLStandaloneSetup extends ArchDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new ArchDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

