/*
 * generated by Xtext
 */
package jp.ac.kyushu.iarch.archdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArchDSLRuntimeModule extends jp.ac.kyushu.iarch.archdsl.AbstractArchDSLRuntimeModule {

}
