/*
* generated by Xtext
*/
package jp.ac.kyushu.iarch.archdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ArchDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return jp.ac.kyushu.iarch.archdsl.ui.internal.ArchDSLActivator.getInstance().getInjector("jp.ac.kyushu.iarch.archdsl.ArchDSL");
	}
	
}
