/*
* generated by Xtext
*/
package jp.ac.kyushu.iarch.archdsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import jp.ac.kyushu.iarch.archdsl.services.ArchDSLGrammarAccess;

public class ArchDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private ArchDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected jp.ac.kyushu.iarch.archdsl.ui.contentassist.antlr.internal.InternalArchDSLParser createParser() {
		jp.ac.kyushu.iarch.archdsl.ui.contentassist.antlr.internal.InternalArchDSLParser result = new jp.ac.kyushu.iarch.archdsl.ui.contentassist.antlr.internal.InternalArchDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getAlternatives_0(), "rule__Model__Alternatives_0");
					put(grammarAccess.getModelAccess().getAlternatives_1(), "rule__Model__Alternatives_1");
					put(grammarAccess.getUncertainInterfaceAccess().getAlternatives_4(), "rule__UncertainInterface__Alternatives_4");
					put(grammarAccess.getSuperMethodAccess().getAlternatives(), "rule__SuperMethod__Alternatives");
					put(grammarAccess.getAltCallAccess().getAlternatives_3_1(), "rule__AltCall__Alternatives_3_1");
					put(grammarAccess.getSuperCallAccess().getAlternatives(), "rule__SuperCall__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getUncertainInterfaceAccess().getGroup(), "rule__UncertainInterface__Group__0");
					put(grammarAccess.getUncertainInterfaceAccess().getGroup_2(), "rule__UncertainInterface__Group_2__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
					put(grammarAccess.getMethodAccess().getGroup_3(), "rule__Method__Group_3__0");
					put(grammarAccess.getMethodAccess().getGroup_3_1(), "rule__Method__Group_3_1__0");
					put(grammarAccess.getAltMethodAccess().getGroup(), "rule__AltMethod__Group__0");
					put(grammarAccess.getAltMethodAccess().getGroup_4(), "rule__AltMethod__Group_4__0");
					put(grammarAccess.getAltMethodAccess().getGroup_4_1(), "rule__AltMethod__Group_4_1__0");
					put(grammarAccess.getAltMethodAccess().getGroup_6(), "rule__AltMethod__Group_6__0");
					put(grammarAccess.getAltMethodAccess().getGroup_6_4(), "rule__AltMethod__Group_6_4__0");
					put(grammarAccess.getAltMethodAccess().getGroup_6_4_1(), "rule__AltMethod__Group_6_4_1__0");
					put(grammarAccess.getOptMethodAccess().getGroup(), "rule__OptMethod__Group__0");
					put(grammarAccess.getOptMethodAccess().getGroup_4(), "rule__OptMethod__Group_4__0");
					put(grammarAccess.getOptMethodAccess().getGroup_4_1(), "rule__OptMethod__Group_4_1__0");
					put(grammarAccess.getParamAccess().getGroup(), "rule__Param__Group__0");
					put(grammarAccess.getBehaviorAccess().getGroup(), "rule__Behavior__Group__0");
					put(grammarAccess.getBehaviorAccess().getGroup_3(), "rule__Behavior__Group_3__0");
					put(grammarAccess.getBehaviorAccess().getGroup_3_1(), "rule__Behavior__Group_3_1__0");
					put(grammarAccess.getUncertainBehaviorAccess().getGroup(), "rule__UncertainBehavior__Group__0");
					put(grammarAccess.getUncertainBehaviorAccess().getGroup_2(), "rule__UncertainBehavior__Group_2__0");
					put(grammarAccess.getUncertainBehaviorAccess().getGroup_5(), "rule__UncertainBehavior__Group_5__0");
					put(grammarAccess.getUncertainBehaviorAccess().getGroup_5_1(), "rule__UncertainBehavior__Group_5_1__0");
					put(grammarAccess.getOptCallAccess().getGroup(), "rule__OptCall__Group__0");
					put(grammarAccess.getAltCallAccess().getGroup(), "rule__AltCall__Group__0");
					put(grammarAccess.getAltCallAccess().getGroup_1(), "rule__AltCall__Group_1__0");
					put(grammarAccess.getAltCallAccess().getGroup_3(), "rule__AltCall__Group_3__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getModelAccess().getInterfacesAssignment_0_0(), "rule__Model__InterfacesAssignment_0_0");
					put(grammarAccess.getModelAccess().getU_interfacesAssignment_0_1(), "rule__Model__U_interfacesAssignment_0_1");
					put(grammarAccess.getModelAccess().getBehaviorsAssignment_1_0(), "rule__Model__BehaviorsAssignment_1_0");
					put(grammarAccess.getModelAccess().getU_behaviorsAssignment_1_1(), "rule__Model__U_behaviorsAssignment_1_1");
					put(grammarAccess.getUncertainInterfaceAccess().getNameAssignment_1(), "rule__UncertainInterface__NameAssignment_1");
					put(grammarAccess.getUncertainInterfaceAccess().getSuperInterfaceAssignment_2_1(), "rule__UncertainInterface__SuperInterfaceAssignment_2_1");
					put(grammarAccess.getUncertainInterfaceAccess().getAltmethodsAssignment_4_0(), "rule__UncertainInterface__AltmethodsAssignment_4_0");
					put(grammarAccess.getUncertainInterfaceAccess().getOptmethodsAssignment_4_1(), "rule__UncertainInterface__OptmethodsAssignment_4_1");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_1(), "rule__Interface__NameAssignment_1");
					put(grammarAccess.getInterfaceAccess().getMethodsAssignment_3(), "rule__Interface__MethodsAssignment_3");
					put(grammarAccess.getMethodAccess().getTypeAssignment_0(), "rule__Method__TypeAssignment_0");
					put(grammarAccess.getMethodAccess().getNameAssignment_1(), "rule__Method__NameAssignment_1");
					put(grammarAccess.getMethodAccess().getParamAssignment_3_0(), "rule__Method__ParamAssignment_3_0");
					put(grammarAccess.getMethodAccess().getParamAssignment_3_1_1(), "rule__Method__ParamAssignment_3_1_1");
					put(grammarAccess.getAltMethodAccess().getTypeAssignment_1(), "rule__AltMethod__TypeAssignment_1");
					put(grammarAccess.getAltMethodAccess().getNameAssignment_2(), "rule__AltMethod__NameAssignment_2");
					put(grammarAccess.getAltMethodAccess().getParamAssignment_4_0(), "rule__AltMethod__ParamAssignment_4_0");
					put(grammarAccess.getAltMethodAccess().getParamAssignment_4_1_1(), "rule__AltMethod__ParamAssignment_4_1_1");
					put(grammarAccess.getAltMethodAccess().getTypeAssignment_6_1(), "rule__AltMethod__TypeAssignment_6_1");
					put(grammarAccess.getAltMethodAccess().getA_nameAssignment_6_2(), "rule__AltMethod__A_nameAssignment_6_2");
					put(grammarAccess.getAltMethodAccess().getParamAssignment_6_4_0(), "rule__AltMethod__ParamAssignment_6_4_0");
					put(grammarAccess.getAltMethodAccess().getParamAssignment_6_4_1_1(), "rule__AltMethod__ParamAssignment_6_4_1_1");
					put(grammarAccess.getOptMethodAccess().getTypeAssignment_1(), "rule__OptMethod__TypeAssignment_1");
					put(grammarAccess.getOptMethodAccess().getNameAssignment_2(), "rule__OptMethod__NameAssignment_2");
					put(grammarAccess.getOptMethodAccess().getParamAssignment_4_0(), "rule__OptMethod__ParamAssignment_4_0");
					put(grammarAccess.getOptMethodAccess().getParamAssignment_4_1_1(), "rule__OptMethod__ParamAssignment_4_1_1");
					put(grammarAccess.getParamAccess().getTypeAssignment_0(), "rule__Param__TypeAssignment_0");
					put(grammarAccess.getParamAccess().getNameAssignment_1(), "rule__Param__NameAssignment_1");
					put(grammarAccess.getBehaviorAccess().getInterfaceAssignment_0(), "rule__Behavior__InterfaceAssignment_0");
					put(grammarAccess.getBehaviorAccess().getCallAssignment_3_0(), "rule__Behavior__CallAssignment_3_0");
					put(grammarAccess.getBehaviorAccess().getCallAssignment_3_1_1(), "rule__Behavior__CallAssignment_3_1_1");
					put(grammarAccess.getBehaviorAccess().getEndAssignment_3_3(), "rule__Behavior__EndAssignment_3_3");
					put(grammarAccess.getUncertainBehaviorAccess().getNameAssignment_1(), "rule__UncertainBehavior__NameAssignment_1");
					put(grammarAccess.getUncertainBehaviorAccess().getSuperInterfaceAssignment_2_1(), "rule__UncertainBehavior__SuperInterfaceAssignment_2_1");
					put(grammarAccess.getUncertainBehaviorAccess().getCallAssignment_5_0(), "rule__UncertainBehavior__CallAssignment_5_0");
					put(grammarAccess.getUncertainBehaviorAccess().getCallAssignment_5_1_1(), "rule__UncertainBehavior__CallAssignment_5_1_1");
					put(grammarAccess.getUncertainBehaviorAccess().getEndAssignment_5_3(), "rule__UncertainBehavior__EndAssignment_5_3");
					put(grammarAccess.getCertainCallAccess().getNameAssignment(), "rule__CertainCall__NameAssignment");
					put(grammarAccess.getOptCallAccess().getNameAssignment_1(), "rule__OptCall__NameAssignment_1");
					put(grammarAccess.getAltCallAccess().getOptAssignment_1_0(), "rule__AltCall__OptAssignment_1_0");
					put(grammarAccess.getAltCallAccess().getNameAssignment_2(), "rule__AltCall__NameAssignment_2");
					put(grammarAccess.getAltCallAccess().getA_nameAssignment_3_1_0(), "rule__AltCall__A_nameAssignment_3_1_0");
					put(grammarAccess.getAltCallAccess().getOptAssignment_3_1_1(), "rule__AltCall__OptAssignment_3_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			jp.ac.kyushu.iarch.archdsl.ui.contentassist.antlr.internal.InternalArchDSLParser typedParser = (jp.ac.kyushu.iarch.archdsl.ui.contentassist.antlr.internal.InternalArchDSLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ArchDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ArchDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
