/*
 * generated by Xtext
 */
package jp.ac.kyushu.iarch.archdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArchDSLUiModule extends jp.ac.kyushu.iarch.archdsl.ui.AbstractArchDSLUiModule {
	public ArchDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
